### ISSUE TITLE
Error when merging

### ISSUE THREAD

**Issue by mrtpcet** [LiroyvH/signal-export#3]
MacOS Ventura 13.6.1

I try to use merging option with the command : 
./sigexport.py --source --source PATH --old PATH

Everything sounds start propely but after few seconds I have the error messages. I have all conversations who seems exported in `ouput` folder but there is no `.html` files, only `.md`and `media`.

```
Copying and renaming attachments

Creating markdown files

Merging old at EXPORT into output directory
No existing files will be deleted or overwritten!

Traceback (most recent call last):
  File "/Users/martin/signal-export/./sigexport.py", line 615, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/signal-export/./sigexport.py", line 607, in main
    merge_with_old(dest, Path(old))
  File "/Users/martin/signal-export/./sigexport.py", line 486, in merge_with_old
    merge_attachments(sub / "media", dir_old / "media")
  File "/Users/martin/signal-export/./sigexport.py", line 444, in merge_attachments
    for f in media_old.iterdir():
  File "/usr/local/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'EXPORT/media/media'
```

**Comment by mrtpcet** [comment]
I have also a lot of files called : `year-month-day_00_None` I can't open
